[tool.poetry]
name = "cloud-surfer"
version = "0.1.0"
description = "Cloud Surfer"
authors = ["Nebullvm Team"]
readme = "README.md"
packages = [{include = "surfer"}]

[tool.poetry.scripts]
surfer = "surfer.cli.main:main"

[tool.poetry.dependencies]
python = "^3.8"
typer = "^0.7.0"
ray = "^2.3.0"
speedster = "^0.2.1"
rich = "^13.3.1"
pyyaml = "^6.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
coverage = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
